# Site wide configuration
#theme: jekyll-theme-minimal
title: Xiangrong Wang (王向荣)
locale: en_US
description: Postdoc in Delft University of Technology
  
owner:
  name: Xiangrong Wang
  bio: "Postdoc in Delft University of Technology."
  email: x.wang-2@tudelft.nl
  avatar: xiangrong.jpeg

#theme: jekyll-theme-leap-day
